image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - dotnet restore src/jr.common/jr.common.csproj
  - dotnet restore src/jr/jr.csproj
  - dotnet restore test/jr.common.tests/jr.common.tests.csproj
  - choco install opencover.portable
  - choco install codecov
build_script:
  - dotnet build src/jr.common/jr.common.csproj
  - dotnet build src/jr/jr.csproj
  - dotnet build test/jr.common.tests/jr.common.tests.csproj
  - dotnet test test/jr.common.tests/jr.common.tests.csproj
test_script:
  - >-
    OpenCover.Console.exe -register:user -target:"C:/Program
    Files/dotnet/dotnet.exe" -targetargs:"test
    --logger:trx;LogFileName=results.trx /p:DebugType=full
    C:\projects\jira-reporting\test\jr.common.tests\jr.common.tests.csproj"
    -filter:"+[jr.common*]* -[jr.common.tests*]* -[jr.common.Jira.Models]*"
    -output:".\coverage.xml"
    -skipautoprops
    -oldstyle
  - codecov -f ".\coverage.xml" -t $(codecov_token)
