language: csharp
dist: trusty
mono: none
dotnet: 2.0.2
install:
- dotnet restore src/jr.common/jr.common.csproj
- dotnet restore src/jr/jr.csproj
- dotnet restore test/jr.common.tests/jr.common.tests.csproj
script:
- dotnet build src/jr.common/jr.common.csproj
- dotnet build src/jr/jr.csproj
- dotnet build test/jr.common.tests/jr.common.tests.csproj
- dotnet test test/jr.common.tests/jr.common.tests.csproj
